POST  http://localhost:5000/user
content-type: application/json

{
    "username":"kjakjs",
    "email":"aks@gmail.com",
    "password":"kjdjdnal"
}
###
POST  http://localhost:5000/user/login
content-type: application/json

{
    "username":"kjakjs",
    "password":"kjdjdnal"
}
###
GET  http://localhost:5000/user/allcards
###
GET  http://localhost:5000/user/logout
###
POST  http://localhost:5000/product
content-type: application/json

{
      "id": 5,
      "title": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
      "price": 695,
      "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
      "category": "jewelery",
      "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
      "rating": {
        "rate": 4.6,
        "count": 400
      }
    }
###
GET  http://localhost:5000/product/list
###
GET  http://localhost:5000/product/list?category=men's clothing
###
GET  http://localhost:5000/product/list?price[lt]=100
###
GET  http://localhost:5000/product/list?sort=-price
###
GET  http://localhost:5000/product/list?fields=title,price
###
GET  http://localhost:5000/product/list?page=2&limit=2